name: Pylint

on: 
  push:
    paths:
      - ston/**
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==3.0.3 PySide6 matplotlib
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=$(git ls-files '*pylintrc') $(git ls-files 'ston/*.py') --output-format=text:pylint_score.txt,colorized --fail-under=9.0
